---
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "fargate-demo-container"
          ContainerPort: 5000
Hooks:
  - BeforeAllowTraffic: deployment_testing
