version: 0.2
phases:
  install:
    commands:
      - pip3 install pipenv
      - pipenv install --system --deploy
  pre_build:
    commands:
      - python tests/flaskblog_unit_test.py -v
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t cicd-demo .
      - docker tag cicd-demo:latest 486790186775.dkr.ecr.us-east-1.amazonaws.com/cicd-demo:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 486790186775.dkr.ecr.us-east-1.amazonaws.com/cicd-demo:latest
artifacts:
  files:
    - '**/*'
  discard-paths: no