---
version: 0.2
## Use newman to run a postman collection.
## The env.json file is created by the pipeline with BASE_URL defined
phases:
  install:
    commands:
      - npm install newman --global
  build:
    commands:
      - newman run -e baseurl.json tests/postman/collection.json

artifacts:
  files:
    - newman/*
