version: 0.2
phases:
  install:
    runtime-versions:
      Docker: aws/codebuild/docker:18.09.0
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t cicd-demo .
      - docker tag cicd-demo:latest 355189840595.dkr.ecr.us-east-1.amazonaws.com/cicd-demo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 355189840595.dkr.ecr.us-east-1.amazonaws.com/cicd-demo:latest
