version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install pipenv
      - pipenv install --system --deploy
  pre_build:
    commands:
      - python tests/flaskblog_unit_test.py -v
artifacts:
  files:
    - "**/*"
  discard-paths: no
