version: 0.2
phases:
  install:
    runtime-versions:
      python: aws/codebuild/python:3.7.1
    commands:
      - pip install pipenv
      - pipenv install --system --deploy
  pre_build:
    commands:
      - python tests/flaskblog_unit_test.py -v
artifacts:
  files:
    - "**/*"
  discard-paths: no
